# BernoulliiNB

In [1]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB

In [ ]:
# X : 단어 포함시 1 미포함시 0
# y : 정상 메일 0 스팸 메일 1

In [6]:
X = np.array([
    [0, 1, 1, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [0, 1, 1, 0]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [7]:
model_bern = BernoulliNB().fit(X, y)

In [8]:
# 예측
x_new = np.array([0, 1, 1, 1])
model_bern.predict_proba([x_new])
# 스팸일 확률이 더 높다

array([[0.34501348, 0.65498652]])

In [9]:
x_new = np.array([0, 0, 1, 1])
model_bern.predict_proba([x_new])
# 스팸일 확률이 더 높다

array([[0.09530901, 0.90469099]])

In [10]:
x_new = np.array([1, 1, 1, 0])
model_bern.predict_proba([x_new])
# 스팸일 확률이 더 높다

array([[0.6371329, 0.3628671]])

# GaussianNB

In [18]:
from sklearn.naive_bayes import GaussianNB

In [38]:
X = np.array([
    [0, 1, 1, 0],
    [1, 1, 1, 1],
    [1, 1, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 0, 1],
    [0, 1, 1, 0],
    [0, 1, 1, 1],
    [1, 0, 1, 0],
    [1, 0, 1, 1],
    [0, 1, 1, 0]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [39]:
#X는 독립변수 데이터 셋, y는 종속변수 데이터 셋
model_NB = GaussianNB().fit(X, y)

In [40]:
x_new = np.array([0, 0, 0, 0])
model_NB.predict_proba([x_new])

array([[0., 1.]])

# MultinomialNB

In [31]:
X = np.array([
    [3, 4, 1, 2],
    [3, 5, 1, 1],
    [3, 3, 0, 4],
    [3, 4, 1, 2],
    [1, 2, 1, 4],
    [0, 0, 5, 3],
    [1, 2, 4, 1],
    [1, 1, 4, 2],
    [0, 1, 2, 5],
    [2, 1, 2, 3]])
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [12]:
from sklearn.naive_bayes import MultinomialNB
model_mult = MultinomialNB().fit(X, y)

In [13]:
x_new = np.array([10, 10, 10, 10])
model_mult.predict_proba([x_new])

array([[0.38848858, 0.61151142]])

In [17]:
x_new = np.array([4, 4, 2, 2])
model_mult.predict_proba([x_new])

array([[0.96466932, 0.03533068]])